theme: mmibordeaux-hugo-theme
_merge: deep
params:
  programs:
    single:
      options:
        logo: false
        website_link: false
languages:
  fr:
    permalinks:
      page:
        bibliography: /bibliographie/:slug/
      section:
        bibliography: /bibliographie/
