theme: mmibordeaux-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true

languages:
  fr:
    permalinks:
      page:
        bibliography: /bibliographie/:slug/
      section:
        bibliography: /bibliographie/
